# Generated by Django 6.0.6 on 2026-06-08 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_deal_next_check_pending_at'),
        ('linkedin', '0009_drop_legacy_pending_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='auto_send',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='connection_note_template',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='campaign',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='follow_up_template',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='linkedinprofile',
            name='connection_status',
            field=models.CharField(choices=[('not_configured', 'Not configured'), ('pending_login', 'Pending login'), ('connected', 'Connected'), ('expired', 'Session expired'), ('checkpoint', 'Checkpoint required'), ('error', 'Error')], default='not_configured', max_length=20),
        ),
        migrations.AddField(
            model_name='linkedinprofile',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkedinprofile',
            name='last_login_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('first_touch', 'First touch'), ('follow_up', 'Follow up')], default='follow_up', max_length=20)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending approval'), ('approved', 'Approved'), ('sent', 'Sent'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending_approval', max_length=20)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_messages', to='linkedin.campaign')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbound_messages', to='crm.deal')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_messages', to='crm.lead')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign', 'status'], name='linkedin_ou_campaig_1f2e49_idx'), models.Index(fields=['deal', 'status'], name='linkedin_ou_deal_id_96a0fa_idx')],
            },
        ),
    ]
